---
- name: Remove legacy key
  apt_key:
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: absent
  tags:
    - journalbeat

- name: Remove legacy repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ journalbeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: False
    state: absent
  tags:
    - journalbeat

- name: Download repo key
  shell:
    cmd: "curl -sSL 'https://artifacts.elastic.co/GPG-KEY-elasticsearch' | gpg --dearmor --output {{ journalbeat_keyring }}"
    creates: "{{ journalbeat_keyring }}"
  tags:
    - journalbeat

- name: Add apt repository
  apt_repository:
    repo: "deb [signed-by={{ journalbeat_keyring }}] https://artifacts.elastic.co/packages/{{ journalbeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: True
    state: present
  tags:
    - journalbeat

- name: Install required packages
  loop:
    - journalbeat
  package:
    name: "{{ item }}"
    state: present
  tags:
    - journalbeat

- name: Drop reference config
  file:
    path: /etc/journalbeat/journalbeat.reference.yml
    state: absent
  tags:
    - journalbeat

- name: Write general config
  notify:
    - Restart journalbeat
  template:
    src: config.j2
    dest: /etc/journalbeat/journalbeat.yml
    validate: journalbeat test config -d -c %s
    owner: root
    group: root
    mode: u=rw,g=,o=
  tags:
    - journalbeat

- name: Start journalbeat service
  systemd:
    name: journalbeat
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - journalbeat

...
