# Standards: 1.2
---
- name: Download repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present
  tags:
    - journalbeat

- name: Add apt repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ journalbeat_major_version }}.x/apt stable main"
    filename: elastic
    update_cache: True
    state: present
  tags:
    - journalbeat

- name: Install required packages
  loop:
    - journalbeat
  package:
    name: "{{ item }}"
    state: present
  tags:
    - journalbeat

- name: Drop reference config
  file:
    path: /etc/journalbeat/journalbeat.reference.yml
    state: absent
  tags:
    - journalbeat

- name: Write general config
  notify:
    - Restart journalbeat
  template:
    src: config.j2
    dest: /etc/journalbeat/journalbeat.yml
    validate: journalbeat test config -d -c %s
  tags:
    - journalbeat

- name: Start journalbeat service
  systemd:
    name: journalbeat
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - journalbeat

...
