# Standards: 0.1
---
- name: Download repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present
  tags:
    - journalbeat

- name: Add apt repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    filename: elastic
    update_cache: True
    state: present
  tags:
    - journalbeat

- name: Install required packages
  loop:
    - journalbeat
  package:
    name: "{{ item }}"
    state: present
  tags:
    - journalbeat

- name: Start journalbeat service
  systemd:
    name: journalbeat
    state: "{{ journalbeat_service_state }}"
    daemon_reload: True
    masked: False
    enabled: "{{ journalbeat_service_enabled }}"
  tags:
    - journalbeat

...
